// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_E1uPcfp7vDfGWhkCKhJrrL0fm9NJvI',
    appId: '1:722000278490:web:a949fcf27fa0304cf346e3',
    messagingSenderId: '722000278490',
    projectId: 'anti-hama1',
    authDomain: 'anti-hama1.firebaseapp.com',
    databaseURL: 'https://anti-hama1-default-rtdb.firebaseio.com',
    storageBucket: 'anti-hama1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7V2PYT4WLjxxUd1i2WhvRAJ6vCZPJGUY',
    appId: '1:722000278490:android:c515fcee2d3ea81ff346e3',
    messagingSenderId: '722000278490',
    projectId: 'anti-hama1',
    databaseURL: 'https://anti-hama1-default-rtdb.firebaseio.com',
    storageBucket: 'anti-hama1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybHxCRmOtQlhXR14Vn4XzWPI0nYWHVcY',
    appId: '1:722000278490:ios:89652eeb865ca602f346e3',
    messagingSenderId: '722000278490',
    projectId: 'anti-hama1',
    databaseURL: 'https://anti-hama1-default-rtdb.firebaseio.com',
    storageBucket: 'anti-hama1.appspot.com',
    iosBundleId: 'com.example.hamaApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybHxCRmOtQlhXR14Vn4XzWPI0nYWHVcY',
    appId: '1:722000278490:ios:89652eeb865ca602f346e3',
    messagingSenderId: '722000278490',
    projectId: 'anti-hama1',
    databaseURL: 'https://anti-hama1-default-rtdb.firebaseio.com',
    storageBucket: 'anti-hama1.appspot.com',
    iosBundleId: 'com.example.hamaApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_E1uPcfp7vDfGWhkCKhJrrL0fm9NJvI',
    appId: '1:722000278490:web:d918f7fd9970c072f346e3',
    messagingSenderId: '722000278490',
    projectId: 'anti-hama1',
    authDomain: 'anti-hama1.firebaseapp.com',
    databaseURL: 'https://anti-hama1-default-rtdb.firebaseio.com',
    storageBucket: 'anti-hama1.appspot.com',
  );
}
